In [2]:
import numpy as np

In [5]:
def randomization(n):
    A = np.random.random(size = n).reshape(n,1)
    return A

In [6]:
def operations(h,w):
    A = np.random.random(size=(h,w))
    B = np.random.random(size =(h,w))
    S = A + B
    return A, B, S

In [7]:
def Norm(A,B):
    S = A + B
    return np.linalg.norm(S)

In [8]:
def neural_network(inputs,weights):
    Z = np.tanh(weights.T.dot(inputs))
    return Z
    

In [9]:
def scalar_function(x,y):
    if(x>y):
        return x*y
    else:
        return x/y

In [10]:
def vector_function(x,y):
    func = np.vectorize(scalar_function)
    return func(x,y)

In [11]:
n = 5
randomization(n)

array([[0.27016793],
       [0.76020036],
       [0.35454491],
       [0.87453185],
       [0.44548262]])

In [14]:
h=3 
w = 3
operations(h,w)

(array([[0.8894826 , 0.76519087, 0.02578496],
        [0.03698622, 0.95756824, 0.08026167],
        [0.85491422, 0.29656855, 0.6113925 ]]),
 array([[0.49619565, 0.17773743, 0.64648839],
        [0.9684591 , 0.89293852, 0.28216512],
        [0.18578049, 0.37227721, 0.44063055]]),
 array([[1.38567826, 0.9429283 , 0.67227335],
        [1.00544532, 1.85050676, 0.36242679],
        [1.04069471, 0.66884576, 1.05202305]]))

In [16]:
A = np.array([[1,2,3]]).T
B = np.array([[1,2,3]]).T
Norm(A,B)

7.483314773547883

In [19]:
inputs = (2,5)
weights = np.array([[9, 2, 3], [3, 4, 5]])
neural_network(inputs,weights)

array([1., 1., 1.])

In [21]:
x = 7
y =10
scalar_function(x,y)

0.7

In [22]:
vector_function(x,y)

array(0.7)